### ISSUE TITLE
Alert: RDDL node has less than 5 connections

### ISSUE THREAD

**Issue by eckelj** [rddl-network/rddl-info#19]
The RDDL network is based on the BFT consensus that requires the approval of 2/3 of the validators. Currently, nine validators exist. The monitoring should alert if a node can only connect to fewer than five validators. This is a potentially unstable state in that no consensus can be notarized to the chain.

The alerting rule should therefore be: node has less than five validator/peer connections.

![image.png](https://images.zenhubusercontent.com/63cfa16c66a52f7dd429dc78/0a13af68-4858-4b89-8be9-758698e476f7)

**Comment by nmarcovici** [comment]
Hello, 

Alert was configured and added to Prometheus:

![image.png](https://images.zenhubusercontent.com/6308c92155a1449c418c9bc3/fbfb006b-a89c-419c-8620-1ea019bb67af)
