### ISSUE TITLE
[alerting] Make AlertManager send resolve mails

### ISSUE THREAD

**Issue by jmastr** [rddl-network/rddl-info#21]
Currently we receive several alerts, but never if an alert is resolved. This involves a lot of manual checking. Please find a way to send mails when the alert was resolved again.

**Comment by nmarcovici** [comment]
AlertManager is configured now to send as well resolve mails.

![image.png](https://images.zenhubusercontent.com/6308c92155a1449c418c9bc3/a000c9d6-5501-4766-aeac-7577583b98bf)
