### ISSUE TITLE
Host influxDB and grafana to show RDDL data

### ISSUE THREAD

**Issue by eckelj** [rddl-network/rddl-info#7]

**Comment by jmastr** [comment]
@eckelj dev or prod cluster?

**Comment by eckelj** [comment]
I suggest production cluster

**Comment by jmastr** [comment]
We have a Grafana up and running at https://info.rddl.io

**Comment by eckelj** [comment]
@jmastr I just need the rddl-info container to be added to the helm chars, should I do that on my own?
